import { Deck } from '../types';

export const SAMPLE_DECKS: Deck[] = [
  {
    id: 'sample-n5-greetings',
    title: '50 Câu chào hỏi & Giao tiếp hàng ngày (N5)',
    description:
      'Các mẫu câu chào hỏi, cảm ơn, xin lỗi và giao tiếp cơ bản nhất trong tiếng Nhật.',
    tags: ['N5', 'Giao tiếp', 'Chào hỏi'],
    color: '#38bdf8',
    isSample: true,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    cards: [
      {
        id: 'greet-1',
        term: 'おはようございます',
        reading: 'ohayou gozaimasu',
        definition: 'Chào buổi sáng (lịch sự)',
        example: '先生、おはようございます。',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'greet-2',
        term: 'こんにちは',
        reading: 'konnichiwa',
        definition: 'Xin chào (ban ngày)',
        example: '皆さん、こんにちは！',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'greet-3',
        term: 'こんばんは',
        reading: 'konbanwa',
        definition: 'Chào buổi tối',
        example: 'こんばんは、お疲れ様です。',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'greet-4',
        term: 'ありがとうございます',
        reading: 'arigatou gozaimasu',
        definition: 'Xin cảm ơn rất nhiều',
        example: '手伝ってくれて、ありがとうございます。',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'greet-5',
        term: 'すみません',
        reading: 'sumimasen',
        definition: 'Xin lỗi / Làm phiền / Xin phép',
        example: 'すみません、水をください。',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'greet-6',
        term: 'おやすみなさい',
        reading: 'oyasuminasai',
        definition: 'Chúc ngủ ngon',
        example: 'それでは、おやすみなさい。',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'greet-7',
        term: 'さようなら',
        reading: 'sayounara',
        definition: 'Tạm biệt (lâu ngày mới gặp lại)',
        example: '先生、さようなら！',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'greet-8',
        term: 'いただきます',
        reading: 'itadakimasu',
        definition: 'Mời cả nhà ăn cơm / Xin nhận',
        example: 'ご飯をいただきます。',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'greet-9',
        term: 'ごちそうさまでした',
        reading: 'gochisousamadeshita',
        definition: 'Cảm ơn vì bữa ăn ngon',
        example: 'とても美味しかったです、ごちそうさまでした。',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'greet-10',
        term: 'お疲れ様でした',
        reading: 'otsukaresamadeshita',
        definition: 'Bạn đã vất vả rồi / Kết thúc công việc',
        example: '今日もお疲れ様でした！',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
    ],
  },
  {
    id: 'sample-n5-kanji-essentials',
    title: 'Bộ Kanji N5 Thiết yếu (Cơ bản nhất)',
    description:
      'Các chữ Hán cơ bản nhất bao gồm số đếm, thiên nhiên, ngày tháng.',
    tags: ['N5', 'Kanji', 'Cơ bản'],
    color: '#a855f7',
    isSample: true,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    cards: [
      {
        id: 'kanji-1',
        term: '日',
        reading: 'Nhật (hi, bi, nichi)',
        definition: 'Ngày, mặt trời, Nhật Bản',
        example: '日曜日 (Chủ nhật)',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'kanji-2',
        term: '月',
        reading: 'Nguyệt (tsuki, getsu, gatsu)',
        definition: 'Tháng, mặt trăng',
        example: '月曜日 (Thứ hai), 一月 (Tháng một)',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'kanji-3',
        term: '火',
        reading: 'Hỏa (hi, ka)',
        definition: 'Lửa',
        example: '火曜日 (Thứ ba), 火事 (Hỏa hoạn)',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'kanji-4',
        term: '水',
        reading: 'Thủy (mizu, sui)',
        definition: 'Nước',
        example: '水曜日 (Thứ tư), 水 (Nước uống)',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'kanji-5',
        term: '木',
        reading: 'Mộc (ki, moku)',
        definition: 'Cây, gỗ',
        example: '木曜日 (Thứ năm)',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'kanji-6',
        term: '金',
        reading: 'Kim (kane, kin)',
        definition: 'Vàng, tiền',
        example: '金曜日 (Thứ sáu), お金 (Tiền)',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'kanji-7',
        term: '土',
        reading: 'Thổ (tsuchi, do)',
        definition: 'Đất',
        example: '土曜日 (Thứ bảy)',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'kanji-8',
        term: '山',
        reading: 'Sơn (yama, san)',
        definition: 'Núi',
        example: '富士山 (Núi Phú Sĩ)',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'kanji-9',
        term: '川',
        reading: 'Xuyên (kawa, gawa)',
        definition: 'Sông',
        example: 'ナイル川 (Sông Nile)',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
      {
        id: 'kanji-10',
        term: '人',
        reading: 'Nhân (hito, jin, nin)',
        definition: 'Người',
        example: '日本人 (Người Nhật), 三人 (Ba người)',
        boxLevel: 0,
        correctCount: 0,
        wrongCount: 0,
      },
    ],
  },
];
